version: '3.1'
services:
  cmd-api-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    container_name: cmd-api-wiremock
    restart: unless-stopped
    ports:
      - "9191:8080"

  check-my-diary-redis:
    image: 'redis:7.0'
    networks:
      - hmpps_int
    ports:
      - '6379:6379'

networks:
  hmpps_int:
