version: '3.1'
services:

  cmd-api-wiremock:
    image: rodolpheche/wiremock
    networks:
      - hmpps_int
    container_name: cmd-api-wiremock
    restart: always
    ports:
      - "9191:8080"

networks:
  hmpps_int:
