services:
  cmd-api-wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps_int
    container_name: cmd-api-wiremock
    restart: unless-stopped
    ports:
      - "9091:8080"

networks:
  hmpps_int:
