---
generic-service:
  nameOverride: check-my-diary

  autoscaling:
    enabled: true

  image:
    repository: quay.io/hmpps/check-my-diary
    tag: latest    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    modsecurity_enabled: false
    path: /
    contextColour: green
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/custom-http-errors: "418"

  livenessProbe:
    httpGet:
      path: /ping
      port: http
    periodSeconds: 30
    initialDelaySeconds: 90
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    httpGet:
      path: /ping
      port: http
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - "check-my-diary"
            topologyKey: kubernetes.io/hostname

  resources:
    requests:
      cpu: 50m

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    WEB_SESSION_TIMEOUT_IN_MINUTES: "20"
    DB_SSL_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    check-my-diary:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      NOTIFY_CLIENT_KEY: "NOTIFY_CLIENT_KEY"
      CMD_API_URL: "CMD_API_URL"
      GOOGLE_ANALYTICS_ID: "GOOGLE_ANALYTICS_ID"

    check-my-diary-rds:
      DATABASE_HOST: "rds_instance_address"
      DATABASE_NAME: "database_name"
      DATABASE_USER: "database_username"
      DATABASE_PASSWORD: "database_password"

    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

generic-prometheus-alerts:
  targetApplication: check-my-diary
# TODO
  runbookUrl: https://dsdmoj.atlassian.net/wiki/spaces/NOM/pages/1514766438/DPS+CloudPlatform+Apps
