apiVersion: v1
kind: Secret
metadata:
  name: check-my-diary-app
type: Opaque
data:
  API_CLIENT_ID: some_base64_encoded_value
  API_CLIENT_SECRET: some_base64_encoded_value
  API_AUTH_ENDPOINT_URL: some_base64_encoded_value
  NOTIFY_CLIENT_KEY: some_base64_encoded_value
  GOOGLE_ANALYTICS_ID: some_base64_encoded_value
