---
generic-service:
  replicaCount: 4

  ingress:
    host: checkmydiary.service.justice.gov.uk
    tlsSecretName: tls-certificate

  env:
    # Note that these times are now in local time, so BST in summer and GMT in winter
    MAINTENANCE_START: "2026-03-01T18:00:00"
    MAINTENANCE_END: "2026-03-01T21:00:00"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    INGRESS_URL: https://checkmydiary.service.justice.gov.uk
    TOKEN_VERIFICATION_API_URL: https://token-verification-api.prison.service.justice.gov.uk
    DPS_HOME_URL: https://digital.prison.service.justice.gov.uk
    CMD_API_URL: https://cmd-api.prison.service.justice.gov.uk

  allowlist:
    # Configure groups as appropriate to give the minimum ingress access required:
    #   digital_staff_and_mojo: devices on the MoJ network
    #   moj_cloud_platform: services on Cloud Platform
    # Other IP allowlist groups are here: 
    # https://github.com/ministryofjustice/hmpps-ip-allowlists/blob/main/ip-allowlist-groups.yaml

    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

  # NOTE: Removing ALL allowlist groups will make the application accessible from the internet. 
  #       If you are intending to do this, please ensure you uncomment the 'modsecurity_enabled=true' 
  #       entry in the ingress above. This will enable WAF protection of the endpoint. You will need 
  #       to configure modsecurity rules to suit your needs. Further information can be found here:
  #       https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html#modsecurity-web-application-firewall




generic-prometheus-alerts:
  ingress2xxEnabled: true
  ingress2xxThreshold: 300

  elastiCacheAlertsClusterIds:
    cp-b603dacd90f94dd7-001: "HMPPS Check my Diary ElastiCache Cluster Node 1"
    cp-b603dacd90f94dd7-002: "HMPPS Check my Diary ElastiCache Cluster Node 2"
