generic-service:
  nameOverride: check-my-diary-sso-prototype
  replicaCount: 1
  productId: null

  poddisruptionbudget:
    enabled: false

  image:
    repository: ghcr.io/ministryofjustice/check-my-diary-sso-prototype
    tag: v1    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    className: default-non-prod
    host: check-my-diary-sso-prototype-stage.apps.live.cloud-platform.service.justice.gov.uk
    modsecurity_enabled: false
    path: /
    tlsSecretName: ""

  livenessProbe:
    httpGet:
      path: /ping
      port: http
    periodSeconds: 30
    initialDelaySeconds: 90
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    httpGet:
      path: /ping
      port: http
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - "check-my-diary-sso-prototype"
            topologyKey: kubernetes.io/hostname

  resources:
    requests:
      cpu: 50m

  # Environment variables to load into the deployment
  env:
    PRODUCT_ID: "cmd-sso-prototype"
    BUILD_NUMBER: "v1"
    GIT_REF: "HAAR-4898-prototype-entra-sso"
    GIT_BRANCH: "HAAR-4898-prototype-entra-sso"
    NODE_ENV: "production"
    WEB_SESSION_TIMEOUT_IN_MINUTES: "20"
    DB_SSL_ENABLED: "false"
    REDIS_ENABLED: "false"
    REDIS_HOST: "not-in-use"
    REDIS_TLS_ENABLED: "false"
    TOKEN_VERIFICATION_ENABLED: "true"
    MAINTENANCE_START: "2025-09-02T10:00:00"
    MAINTENANCE_END: "2025-09-02T10:30:00"
    HMPPS_AUTH_URL: "https://sign-in-stage.hmpps.service.justice.gov.uk/auth"
    INGRESS_URL: https://check-my-diary-sso-prototype-stage.apps.live.cloud-platform.service.justice.gov.uk/
    TOKEN_VERIFICATION_API_URL: https://token-verification-api-stage.prison.service.justice.gov.uk
    DPS_HOME_URL: https://digital-dev.prison.service.justice.gov.uk
    ENVIRONMENT_NAME: STAGE
    CMD_API_URL: http://cmd-api-mock.hmpps-auth-stage.svc.cluster.local
    NOMIS_USER_ROLES_API_URL: https://nomis-user-roles-api-stage.prison.service.justice.gov.uk

  namespace_secrets:
    check-my-diary-sso-prototype:
      SESSION_SECRET: "SESSION_SECRET"
      GOOGLE_ANALYTICS_ID: "GOOGLE_ANALYTICS_ID"
      AUTH_CODE_CLIENT_ID: "CHECK_MY_DIARY_POC_AUTH_CODE_CLIENT_ID"
      AUTH_CODE_CLIENT_SECRET: "CHECK_MY_DIARY_POC_AUTH_CODE_CLIENT_SECRET"
      CHECK_MY_DIARY_POC_CLIENT_ID: "CHECK_MY_DIARY_POC_CLIENT_ID"
      CHECK_MY_DIARY_POC_CLIENT_SECRET: "CHECK_MY_DIARY_POC_CLIENT_SECRET"
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"

  allowlist:
    groups:
      - global_protect

generic-prometheus-alerts:
  businessHoursOnly: true
  targetApplication: check-my-diary-sso-prototype
  alertSeverity: hmpps_tech_non_prod
