---
generic-service:
  replicaCount: 2

  ingress:
    host: check-my-diary-preprod.prison.service.justice.gov.uk
    tlsSecretName: check-my-diary-cert
    className: modsec-non-prod

  env:
    # Note that these times are now in local time, so BST in summer and GMT in winter
    MAINTENANCE_START: "2025-09-02T10:00:00"
    MAINTENANCE_END: "2025-09-02T10:30:00"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    INGRESS_URL: https://check-my-diary-preprod.prison.service.justice.gov.uk
    TOKEN_VERIFICATION_API_URL: https://token-verification-api-preprod.prison.service.justice.gov.uk
    DPS_HOME_URL: https://digital-preprod.prison.service.justice.gov.uk
    ENVIRONMENT_NAME: PRE-PRODUCTION
    CMD_API_URL: https://cmd-api-preprod.prison.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '25 6 * * 1-5' # Start at 6.25am UTC Monday-Friday
    shutdown: '45 21 * * 1-5' # Stop at 9.45pm UTC Monday-Friday

  allowlist:
    # Configure groups as appropriate to give the minimum ingress access required:
    #   digital_staff_and_mojo: devices on the MoJ network
    #   moj_cloud_platform: services on Cloud Platform
    # Other IP allowlist groups are here: 
    # https://github.com/ministryofjustice/hmpps-ip-allowlists/blob/main/ip-allowlist-groups.yaml

    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

  # NOTE: Removing ALL allowlist groups will make the application accessible from the internet. 
  #       If you are intending to do this, please ensure you uncomment the 'modsecurity_enabled=true' 
  #       entry in the ingress above. This will enable WAF protection of the endpoint. You will need 
  #       to configure modsecurity rules to suit your needs. Further information can be found here:
  #       https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html#modsecurity-web-application-firewall




generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod

  elastiCacheAlertsClusterIds:
    cp-8b1a161abe55dd23-001: "HMPPS Check my Diary ElastiCache Cluster Node 1"
    cp-8b1a161abe55dd23-002: "HMPPS Check my Diary ElastiCache Cluster Node 2"
