apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: check-my-diary
  name: check-my-diary
spec:
  maxReplicas: {{ .Values.maxReplicaCount }}
  minReplicas: {{ .Values.replicaCount }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: check-my-diary
  targetCPUUtilizationPercentage: 80
