apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: check-my-diary
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.maxReplicaCount }}
  minReplicas: {{ .Values.replicaCount }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: check-my-diary
  targetCPUUtilizationPercentage: 80
