name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "31 5 * * MON-FRI" # Every weekday at 05:31 UTC
jobs:
  security-kotlin-trivy-check:
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v0.6 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
